server:
  servlet:
    context-path: /api/sorter
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
data:
mongodb:
uri: mongodb://localhost/test